### ISSUE TITLE
Request for Information on Sidebar's creation Using Off-Screen Api.

### ISSUE THREAD

**Issue by GibsonRuitiari** [varabyte/kotter#106]
Hey there, I wanted to enquire whether it is possible to create menus/sidebars (favorites & Channels section that is) like shown in the image

I was thinking of using off-screen api, in your library, to do that but I feel like I might be stretching the limits of the library.

![268214790-5b85343f-d098-48d8-ae98-4bd1e99e0a8b](https://github.com/varabyte/kotter/assets/88240355/424447f3-f80b-4a7b-a004-de169aa5b442)

Would like your opinion on this. Thanks

**Comment by GibsonRuitiari** [comment]
Makes sense. Thanks for your prompt reply. I think I will just restructure the application to something else that is supported by the library.
Closing this now :)

**Comment by bitspittle** [comment]
@grnt426 just checking, is this something like what your DSL experiment is?
