### ISSUE TITLE
Strange behaviour with key presses after using onKeyPressed or runUntilKeyPressed

### ISSUE THREAD

**Issue by jack-darlington-at** [varabyte/kotter#116]
**Describe the bug**
When using `onKeyPressed` if I try and launch `vi` in the same session, vi will no longer respond correctly to key presses

**To Reproduce**
1. Code: 
```
section {
        textLine("Wait for q")
    }.runUntilKeyPressed(Keys.Q)

platform.posix.system("vi test")
```
2. Run the following, and try to use vi 

**Expected behavior**
`vi` works as expected

**Desktop (please complete the following information):**
 - OS: macosxArm64
 - Version 1.1.2

**Additional context**
I think it may be related to this still consuming keys based on this comment:

```// Once created, we keep it alive for the session, because Flow is designed to be collected multiple times, meaning
// there's no reason for us to keep recreating it. It's pretty likely that if a session uses input in one block, it
// will use input again in others. (We can always revisit this decision later and scope this to a Section lifecycle
// instead)
private val KeyFlowKey = Session.Lifecycle.createKey<Flow<Key>>()```

**Comment by bitspittle** [comment]
Hey! Sorry I missed this bug until just now. It's been crazy over here as I was preparing for a talk (that I finally gave last Friday) and it just consumed all my time.

Would you be able to try wrapping your logic in a session? As in:

```
session {
   section {
        textLine("Wait for q")
    }.runUntilKeyPressed(Keys.Q)
}

platform.posix.system("vi test")
```

If that works for you, I could think about making that logic apply to a section scope instead. However, part of me feels that within a session, I really think that Kotter should be thought of as the main process in control of the keyboard. Trying to design a system that plays nice with external processes is probably not something that will scale, I worry.

Of course, if you can let me know your use-case and why you wouldn't want to exit a session before launching vi, please let me know. Also, it's possible that wrapping things in a session wouldn't work! So let me know that as well if you can.

**Comment by bitspittle** [comment]
I'm going to close this issue as there hasn't been a reply for a while, but if you ping it, I can open it again.
