### ISSUE TITLE
Host Kotter on mavenCentral

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kotter#45]

**Comment by Mishkun** [comment]
@bitspittle  any updates on this?

**Comment by bitspittle** [comment]
No updates! I've just been lazy and didn't realize anyone was waiting for it.

I can prioritize it soon. It won't be for a week at least as I'm actually going on vacation this weekend, but I can look into it next week. It's probably time :) I have a few other projects (kobweb, truthish) I've been meaning to update as well.

**Comment by bitspittle** [comment]
Just an FYI that I haven't forgotten about this! I just haven't been able to get to it yet. Trying to angle for time this week.

**Comment by bitspittle** [comment]
Woof what crazy weeks it's been :dizzy_face: but I'm on top of things at the moment. Looking into this today.

**Comment by bitspittle** [comment]
Kickstarting the process with Sonatype. Hopefully should be unblocked on their side in ~2 business days. We'll see! :crossed_fingers:

**Comment by bitspittle** [comment]
Alright, it worked for me! Let me know if it doesn't work for any of you.
