### ISSUE TITLE
Timing issues with aside sections

### ISSUE THREAD

**Issue by cedriessen** [varabyte/kotter#86]
First: Great library, I like it a lot!

**Describe the bug**

That very simple demo below always only yields
```
Do something...
```
swallowing all the asides.

```kotlin
session {
  section {
    textLine("Do something...")
  }.run {
    aside { textLine(" - a") }
    aside { textLine(" - b") }
    aside { textLine(" - b") }
    aside { textLine(" - f") }
    // to be replaced
  }
}
```

If I replace `// to be replaced` at the end of the `run` block with something like `Thread.sleep(1)` (yes 1 ms is enough) or a "heavy" computation that takes some ms everything's printed out. I am suspecting a timing issue. 

Do you have any thoughts?

**Comment by bitspittle** [comment]
Hey, I am **so** sorry for the long delay in replying. I missed the notification and just saw it now! Especially, I _really_ appreciate your quick example to repro.

For now, to avoid using a sleep, I would recommend solving this using `runUntilSignal`:

```
session {
  section {
    textLine("Do something...")
  }.runUntilSignal {
    aside { textLine(" - a") }
    aside { textLine(" - b") }
    aside { textLine(" - b") }
    aside { textLine(" - f") }
    signal()
  }
}
```

Will investiagate. I suspect what should happen is the run block shouldn't consider itself done as long as there are any remaining `aside` blocks queuend up for rendering. It's been a while since I looked at this code though and it might be a hairy, subtle interaction...

**Comment by bitspittle** [comment]
OK, looked a little more. What's happening is that a section is responsible for processing any aside blocks enqueued by the `run` method. 

But your section is ending so fast, it shuts down and then the `run` block continues to add more `aside` blocks. (`section` and `run` are two different threads working at the same time)

I'm experimenting to see if it's trivial enough to detect, when the `run` method finishes, if one or more asides are still left, at which point, we kick off one more render request for the section (which should print out those remaining asides). But so far the code is fighting me a bit...

**Comment by cedriessen** [comment]
Thanks for looking into it and providing me with a solution.

**Comment by bitspittle** [comment]
OK, got it. It wasn't really that hard to fix once I got familiar with the code again. This was a great bug -- thanks for reporting!

I also added a unit test for this issue, and ran it _a lot_. It seems to be a solid fix.

**Comment by cedriessen** [comment]
Ok. As mentioned on the other issue I will give it a try. Thanks for investing your time helping me out with that.

**Comment by bitspittle** [comment]
You bet, and no rush! I just wanted you to know things were available at
your convenience.

Thanks for your feedback, it helped me make Kotter better.

**Comment by cedriessen** [comment]
Just wanted to let you know: I've upgraded to 1.0.0-rc1 and things work like a charm :-)
